# Generated by Django 4.0.1 on 2022-02-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seaview', '0002_auto_20220213_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
