# Generated by Django 3.1.3 on 2022-02-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seaview', '0002_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
