# Generated by Django 3.1.3 on 2022-02-11 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seaview', '0003_auto_20220204_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
    ]
