# Generated by Django 4.0.1 on 2022-02-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seaview', '0003_auto_20220204_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
