# Generated by Django 4.0.1 on 2022-02-14 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seaview', '0003_alter_reply_id_alter_review_id'),
        ('seaview', '0004_auto_20220214_1035'),
    ]

    operations = [
    ]
