# Generated by Django 4.0.1 on 2022-02-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seaview', '0004_alter_reply_id_alter_review_id'),
        ('seaview', '0006_reply_author'),
    ]

    operations = [
    ]
