# Generated by Django 3.1.3 on 2022-02-11 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seaview', '0004_alter_reply_id_alter_review_id'),
        ('seaview', '0006_reply_author'),
    ]

    operations = [
    ]
