# Generated by Django 4.0.1 on 2022-02-04 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mainphoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
