# Generated by Django 4.0.1 on 2022-02-04 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subsite', '0002_auto_20220204_1126'),
        ('subsite', '0003_alter_post_postname'),
    ]

    operations = [
    ]
