# Generated by Django 3.1.3 on 2022-02-04 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subsite', '0003_alter_post_postname'),
        ('subsite', '0002_auto_20220204_1126'),
    ]

    operations = [
    ]
