# Generated by Django 3.1.3 on 2022-02-08 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subsite', '0004_merge_20220204_1634'),
        ('subsite', '0004_merge_20220204_1524'),
    ]

    operations = [
    ]
